# Generated by Django 4.1 on 2022-08-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flightApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="email",
            field=models.CharField(max_length=50),
        ),
    ]
