# Generated by Django 4.1 on 2022-08-29 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flightApp", "0003_alter_reservation_flight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="flightApp.passenger"
            ),
        ),
    ]
